name: Drone
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: Compiles
        run: make
